import {span,captureFault} from './telemetry.js';
import {createHash,randomBytes,createCipheriv,createDecipheriv,createSign,createHmac,timingSafeEqual} from 'node:crypto';
import {neon} from '@neondatabase/serverless';

export type ProductEnv=Record<string,string|undefined>;
export type Query=(text:string,params?:any[])=>Promise<any[]>;
export class ProductError extends Error {constructor(public status:number,message:string,public expected=false){super(message)}}
export const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
export const random=()=>randomBytes(32).toString('base64url');
export const json=(value:any,status=200,headers:Record<string,string>={})=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store','X-Content-Type-Options':'nosniff',...headers}});
export const redirect=(url:string,cookie?:string)=>new Response(null,{status:302,headers:{Location:url,'Cache-Control':'no-store',...(cookie?{'Set-Cookie':cookie}:{})}});
export const cookie=(name:string,value:string,age:number)=>`${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${age}`;
export const cookies=(req:Request)=>Object.fromEntries((req.headers.get('cookie')||'').split(';').map(p=>p.trim().split(/=(.*)/s).slice(0,2)));
export function encryptionKey(env:ProductEnv){const key=Buffer.from(env.TOKEN_ENCRYPTION_KEY||'','hex');if(key.length!==32)throw new ProductError(503,'Account encryption is not configured.');return key;}
export function encrypt(value:any,env:ProductEnv){const iv=randomBytes(12),cipher=createCipheriv('aes-256-gcm',encryptionKey(env),iv);const encrypted=Buffer.concat([cipher.update(JSON.stringify(value)),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),encrypted]).toString('base64url');}
export function decrypt(value:string,env:ProductEnv){const data=Buffer.from(value,'base64url'),cipher=createDecipheriv('aes-256-gcm',encryptionKey(env),data.subarray(0,12));cipher.setAuthTag(data.subarray(12,28));return JSON.parse(Buffer.concat([cipher.update(data.subarray(28)),cipher.final()]).toString());}
export function appJwt(env:ProductEnv){if(!env.GITHUB_APP_ID||!env.GITHUB_APP_PRIVATE_KEY_B64)throw new ProductError(503,'GitHub App is not configured.');const now=Math.floor(Date.now()/1000);const data=Buffer.from(JSON.stringify({alg:'RS256',typ:'JWT'})).toString('base64url')+'.'+Buffer.from(JSON.stringify({iat:now-60,exp:now+540,iss:env.GITHUB_APP_ID})).toString('base64url');return data+'.'+createSign('RSA-SHA256').update(data).sign(Buffer.from(env.GITHUB_APP_PRIVATE_KEY_B64,'base64'),'base64url');}
export function validSignature(raw:string,signature:string|null,secret:string){if(!signature||!/^sha256=[a-f0-9]{64}$/.test(signature))return false;const expected='sha256='+createHmac('sha256',secret).update(raw).digest('hex');return timingSafeEqual(Buffer.from(expected),Buffer.from(signature));}
export function localReturn(value:string|null){return value&&value.startsWith('/')&&!value.startsWith('//')&&!value.includes('\\')&&value.length<1000&&!value.startsWith('/api/')?value:'/dashboard';}
export function repositoryName(value:any){if(typeof value!=='string'||!/^[-\w.]+\/[-\w.]+$/.test(value)||value.length>200)throw new ProductError(400,'Choose a valid GitHub repository.');return value;}

export class Product {
 sql:Query;
 constructor(public env:ProductEnv,public fetcher:typeof fetch=fetch,query?:Query){const execute=query||((text:string,params:any[]=[])=>neon(env.DATABASE_URL! ).query(text,params) as Promise<any[]>);this.sql=(text,params)=>span('database',()=>execute(text,params));}
 async github(path:string,token:string,method='GET',body?:any){
  const r=await span('github',()=>this.fetcher('https://api.github.com'+path,{method,headers:{Authorization:'Bearer '+token,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2026-03-10','User-Agent':'PatchGoblin','Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(20000)}));
  if(!r.ok){if(r.status===429||(r.status===403&&r.headers.get('x-ratelimit-remaining')==='0'))throw new ProductError(429,'GitHub rate limit reached. Retry after '+(r.headers.get('retry-after')||'60')+' seconds.');throw new ProductError(r.status===401?401:r.status===404?404:502,`GitHub request failed (${r.status}). Reconnect or check installation permissions.`);}
  return r.status===204?null:r.json();
 }
 async oauth(body:Record<string,string>,identity=false){const r=await span('oauth',()=>this.fetcher('https://github.com/login/oauth/access_token',{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json'},body:JSON.stringify({client_id:identity?this.env.GITHUB_OAUTH_CLIENT_ID:this.env.GITHUB_CLIENT_ID,client_secret:identity?this.env.GITHUB_OAUTH_CLIENT_SECRET:this.env.GITHUB_CLIENT_SECRET,...body}),signal:AbortSignal.timeout(20000)}));const result=await r.json();if(!r.ok||!result.access_token)throw new ProductError(r.status>=500?502:401,'GitHub authorization expired or was declined. Sign in again.');return result;}
 async session(req:Request){const value=cookies(req)['__Host-pg-session'];if(!value)return null;const rows=await this.sql('SELECT a.*,s.csrf,s.token_hash FROM pg_sessions s JOIN pg_accounts a ON a.id=s.account_id WHERE s.token_hash=$1 AND s.expires_at>now()',[hash(value)]);return rows[0]||null;}
 async userToken(account:any){if(!account.credentials)throw new ProductError(403,'Authorize selected repository access in onboarding.');let auth=decrypt(account.credentials,this.env);if(account.token_expires_at&&new Date(account.token_expires_at).getTime()<Date.now()+60000){if(!auth.refresh_token)throw new ProductError(401,'Authorize repository access again in onboarding.');
  const lease=await this.sql("UPDATE pg_accounts SET refresh_lease_until=now()+interval '30 seconds' WHERE id=$1 AND credentials=$2 AND (refresh_lease_until IS NULL OR refresh_lease_until<now()) RETURNING id",[account.id,account.credentials]);
  if(lease.length){try{const result=await this.oauth({grant_type:'refresh_token',refresh_token:auth.refresh_token});await this.sql('UPDATE pg_accounts SET credentials=$2,token_expires_at=$3,refresh_expires_at=$4,refresh_lease_until=NULL,updated_at=now() WHERE id=$1 AND credentials=$5',[account.id,encrypt(result,this.env),new Date(Date.now()+(result.expires_in||28800)*1000).toISOString(),result.refresh_token_expires_in?new Date(Date.now()+result.refresh_token_expires_in*1000).toISOString():null,account.credentials]);}catch(error){await this.sql('UPDATE pg_accounts SET refresh_lease_until=NULL WHERE id=$1',[account.id]);throw error;}}
  else for(let attempt=0;attempt<6;attempt++){const current=(await this.sql('SELECT credentials,token_expires_at FROM pg_accounts WHERE id=$1',[account.id]))[0];if(!current)throw new ProductError(401,'Account no longer exists.');if(current.credentials!==account.credentials){auth=decrypt(current.credentials,this.env);return auth.access_token;}await new Promise(resolve=>setTimeout(resolve,500));}
  const current=(await this.sql('SELECT credentials,token_expires_at FROM pg_accounts WHERE id=$1',[account.id]))[0];if(!current||new Date(current.token_expires_at).getTime()<Date.now()+60000)throw new ProductError(503,'GitHub access is being renewed. Retry in a moment.',true);auth=decrypt(current.credentials,this.env);
 }return auth.access_token;}
 async installationToken(id:number,repoId?:number){const value=await this.github(`/app/installations/${id}/access_tokens`,appJwt(this.env),'POST',repoId?{repository_ids:[repoId]}:{});return value.token;}
 async sync(account:any){const token=await this.userToken(account);const installations=[];for(let page=1;page<=10;page++){const data=await this.github(`/user/installations?per_page=100&page=${page}`,token);installations.push(...data.installations.filter((x:any)=>String(x.app_id)===this.env.GITHUB_APP_ID));if(data.installations.length<100)break;}
  const seen:number[]=[];
  for(const i of installations){await this.sql('INSERT INTO pg_installations(id,account_login,account_type,active) VALUES($1,$2,$3,$4) ON CONFLICT(id) DO UPDATE SET account_login=EXCLUDED.account_login,account_type=EXCLUDED.account_type,active=EXCLUDED.active,updated_at=now()',[i.id,i.account.login,i.account.type,!i.suspended_at]);if(i.suspended_at)continue;
   for(let page=1;page<=10;page++){const data=await this.github(`/user/installations/${i.id}/repositories?per_page=100&page=${page}`,token);for(const r of data.repositories){seen.push(r.id);await this.sql('INSERT INTO pg_repositories(id,installation_id,full_name,default_branch,private) VALUES($1,$2,$3,$4,$5) ON CONFLICT(id) DO UPDATE SET full_name=EXCLUDED.full_name,default_branch=EXCLUDED.default_branch,private=EXCLUDED.private,installation_id=EXCLUDED.installation_id,active=true,updated_at=now()',[r.id,i.id,r.full_name,r.default_branch,r.private]);await this.sql('INSERT INTO pg_repository_members(account_id,repo_id,can_push,can_admin) VALUES($1,$2,$3,$4) ON CONFLICT(account_id,repo_id) DO UPDATE SET can_push=EXCLUDED.can_push,can_admin=EXCLUDED.can_admin',[account.id,r.id,!!r.permissions?.push,!!r.permissions?.admin]);}if(data.repositories.length<100)break;}
  }
  await this.sql('DELETE FROM pg_repository_members WHERE account_id=$1 AND NOT(repo_id=ANY($2::bigint[]))',[account.id,seen]);return this.repositories(account.id);
 }
 async repositories(id:number){return this.sql('SELECT r.*,m.can_push,m.can_admin,i.account_type,i.account_login FROM pg_repository_members m JOIN pg_repositories r ON r.id=m.repo_id JOIN pg_installations i ON i.id=r.installation_id WHERE m.account_id=$1 AND r.active AND i.active ORDER BY r.full_name',[id]);}
 async authorize(account:any,name:string,write=false,admin=false){repositoryName(name);const row=(await this.sql('SELECT r.*,i.active AS installation_active FROM pg_repositories r JOIN pg_installations i ON i.id=r.installation_id WHERE full_name=$1 AND r.active AND i.active',[name]))[0];if(!row)throw new ProductError(404,'Repository is not installed or access was removed.');const token=await this.userToken(account);const actual=await this.github(`/repos/${name}`,token);if(actual.id!==Number(row.id)||write&&!actual.permissions?.push||admin&&!actual.permissions?.admin)throw new ProductError(403,'Your GitHub permissions do not allow this action.');
  // A user token cannot access a repository outside the App installation intersection.
  const current=await this.github(`/repos/${name}/installation`,appJwt(this.env));if(current.id!==Number(row.installation_id)||current.suspended_at)throw new ProductError(403,'Installation access has changed. Refresh your repositories.');return {row,token:await this.installationToken(Number(row.installation_id),Number(row.id)),actual};
 }
 async wake(){if(!this.env.WORKER_URL||!this.env.WORKER_WAKE_TOKEN)return;for(let i=0;i<2;i++)try{const r=await span('wake',()=>this.fetcher(this.env.WORKER_URL+'/wake',{method:'POST',headers:{Authorization:'Bearer '+this.env.WORKER_WAKE_TOKEN},signal:AbortSignal.timeout(12000)}));if(r.ok)return;if(i===1)captureFault(new Error('Worker wake failed'),'wake');}catch(error){if(i===1)captureFault(error,'wake');}}
}
