CREATE TABLE IF NOT EXISTS patchgoblin_jobs (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 owner_key text NOT NULL,
 idempotency_key text NOT NULL,
 request jsonb NOT NULL,
 state jsonb NOT NULL DEFAULT '{}',
 status text NOT NULL DEFAULT 'queued',
 created_at timestamptz NOT NULL DEFAULT now(),
 updated_at timestamptz NOT NULL DEFAULT now(),
 cancelled_at timestamptz,
 lease_token uuid,
 lease_expires_at timestamptz,
 sandbox_id text,
 legacy_issue_url text,
 UNIQUE (owner_key,idempotency_key),
 CHECK (octet_length(request::text)<=30000),
 CHECK (octet_length(state::text)<=250000)
);
CREATE INDEX IF NOT EXISTS patchgoblin_jobs_queue ON patchgoblin_jobs (status,created_at);
CREATE INDEX IF NOT EXISTS patchgoblin_jobs_owner ON patchgoblin_jobs (owner_key,created_at DESC);

CREATE OR REPLACE FUNCTION patchgoblin_expire() RETURNS void LANGUAGE plpgsql AS $$
BEGIN
 UPDATE patchgoblin_jobs SET lease_token=NULL,lease_expires_at=NULL,updated_at=now(),
  status=CASE WHEN status IN ('verified','submitted','unsupported','failed','cancelled') THEN status ELSE 'failed' END,
  state=CASE
   WHEN status='verified' THEN state || jsonb_build_object('pr_error','Worker stopped after verification; retry PR submission.')
   WHEN status IN ('submitted','unsupported','failed','cancelled') THEN state
   ELSE state || jsonb_build_object('status','failed','diagnosis','Worker lease expired; an explicit new job is required.') END
 WHERE lease_token IS NOT NULL AND lease_expires_at<now();
END $$;

CREATE OR REPLACE FUNCTION patchgoblin_enqueue(p_owner text,p_key text,p_request jsonb)
RETURNS SETOF patchgoblin_jobs LANGUAGE plpgsql AS $$
BEGIN
 PERFORM pg_advisory_xact_lock(762437);
 PERFORM patchgoblin_expire();
 IF EXISTS (SELECT 1 FROM patchgoblin_jobs WHERE owner_key=p_owner AND idempotency_key=p_key) THEN
  RETURN QUERY SELECT * FROM patchgoblin_jobs WHERE owner_key=p_owner AND idempotency_key=p_key;
  RETURN;
 END IF;
 IF (SELECT count(*) FROM patchgoblin_jobs WHERE owner_key=p_owner AND created_at>now()-interval '1 hour')>=8 THEN
  RAISE EXCEPTION 'PG_RATE_LIMIT';
 END IF;
 IF EXISTS (SELECT 1 FROM patchgoblin_jobs WHERE owner_key=p_owner AND status NOT IN ('verified','submitted','unsupported','failed','cancelled')) THEN
  RAISE EXCEPTION 'PG_ACTIVE_JOB';
 END IF;
 RETURN QUERY INSERT INTO patchgoblin_jobs(owner_key,idempotency_key,request)
 VALUES(p_owner,p_key,p_request) RETURNING *;
END $$;

CREATE OR REPLACE FUNCTION patchgoblin_claim(p_lease uuid)
RETURNS SETOF patchgoblin_jobs LANGUAGE plpgsql AS $$
DECLARE v_id bigint;
BEGIN
 PERFORM pg_advisory_xact_lock(762438);
 PERFORM patchgoblin_expire();
 IF EXISTS (SELECT 1 FROM patchgoblin_jobs WHERE lease_token IS NOT NULL) THEN RETURN; END IF;
 SELECT id INTO v_id FROM patchgoblin_jobs WHERE status='queued' AND cancelled_at IS NULL ORDER BY created_at LIMIT 1 FOR UPDATE SKIP LOCKED;
 IF v_id IS NULL THEN RETURN; END IF;
 RETURN QUERY UPDATE patchgoblin_jobs SET lease_token=p_lease,lease_expires_at=now()+interval '15 minutes',updated_at=now()
 WHERE id=v_id RETURNING *;
END $$;
