import React,{useState,useEffect,useCallback} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowUpRight,ArrowRight,GitBranch,GitPullRequest,Check,CheckCircle2,Clock,Code2,FileDiff,FlaskConical,History,Loader2,Play,Plus,ShieldCheck,Sparkles,Terminal,TriangleAlert,Wrench,X,ChevronRight,BookOpen,GitFork,Layers3,RotateCw} from 'lucide-react';
import {demoJob} from './demo';
import './style.css';
// Sites serves the homepage separately from the Worker. Navigate directly on
// the retired origin, including tabs with a cached API redirect.
if(location.origin==='https://patchgoblin.wauul.chatgpt.site')location.replace('https://patchgoblin.vercel.app/'+location.search+location.hash);
type Job=Record<string,any>;
const stages=['inspect','reproduce','investigate','patch','verify','submit'];
const finished=['submitted','unsupported','failed','cancelled'];
async function api(path:string,body?:any){const r=await fetch('/api'+path,{cache:'no-store',...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed');return data;}
const duration=(n:any)=>typeof n==='number'?(n<60?`${n.toFixed(1)}s`:`${Math.floor(Math.round(n)/60)}m ${Math.round(n)%60}s`):'Unavailable';
function Mascot({small=false}:{small?:boolean}){return <svg className={small?'mascot small':'mascot'} viewBox="0 0 64 64" aria-label="PatchGoblin mascot"><path d="M8 20l17 7h14l17-7-9 22-9 12H26l-9-12z" fill="currentColor"/><path d="M21 33l9 3-9 3m22-6l-9 3 9 3" fill="#1b2d29"/><path d="M27 45h10" stroke="#1b2d29" strokeWidth="3" strokeLinecap="round"/></svg>}
function App(){
 const [page,setPage]=useState('workbench'),[bootstrap,setBootstrap]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[history,setHistory]=useState<Job[]>([]),[job,setJob]=useState<Job|null>(null),[mode,setMode]=useState('repair'),[repo,setRepo]=useState(''),[runs,setRuns]=useState<any[]>([]),[run,setRun]=useState(''),[ref,setRef]=useState('main'),[tab,setTab]=useState('diagnosis'),[demo,setDemo]=useState(false);
 const refreshHistory=useCallback(async()=>{try{setHistory(await api('/jobs'));}catch{}},[]);
 useEffect(()=>{api('/bootstrap?cutover=vercel').then(data=>{if(data.production_url){const target=new URL(data.production_url);if(target.protocol==='https:'&&target.origin!==location.origin)location.replace(target.origin+location.search);return;}setBootstrap(data);if(data.repositories?.length)setRepo(data.repositories[0].name);if(data.connected){refreshHistory();const id=new URLSearchParams(location.search).get('job');if(id&&/^\d+$/.test(id))api('/jobs/'+id).then(setJob).catch(e=>setError(e.message));}}).catch(e=>setError(e.message));},[refreshHistory]);
 useEffect(()=>{if(!repo||!bootstrap?.connected)return;setRuns([]);setRun('');api('/runs?repo='+encodeURIComponent(repo)).then(data=>{setRuns(data);if(data.length)setRun(String(data[0].id));}).catch(e=>setError(e.message));},[repo,bootstrap?.connected]);
 const remotePending=job?.status==='submitted'&&(!job.remote_ci?.length||job.remote_ci.some((r:any)=>r.status!=='completed'))&&Date.now()-Date.parse(job.created_at)<1800000;
 useEffect(()=>{if(!job?.id||demo||(finished.includes(job.status)&&!remotePending))return;let disposed=false;
  const tick=async()=>{try{let next=await api(`/jobs/${job.id}/sync`,{});if(next.status==='verified'&&(!bootstrap?.worker_submission||next.pr_error))next=await api(`/jobs/${job.id}/submit`,{});if(!disposed)setJob(next);}catch(e){if(!disposed)setError((e as Error).message);}};
  const timer=setInterval(tick,8000);return()=>{disposed=true;clearInterval(timer);};
 },[job?.id,job?.status,job?.remote_ci?.map((r:any)=>r.status+':'+r.conclusion).join('|'),remotePending,demo,bootstrap?.worker_submission]);
 async function start(){setBusy(true);setError('');setDemo(false);try{const key=crypto.randomUUID();const next=await api('/jobs',{repo,mode,run_id:mode==='repair'?Number(run):null,ref,key});setJob(next);window.history.replaceState(null,'','?job='+next.id);setTab('diagnosis');refreshHistory();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function load(id:number){setError('');try{setJob(await api('/jobs/'+id));window.history.replaceState(null,'','?job='+id);setDemo(false);setPage('workbench');}catch(e){setError((e as Error).message);}}
 async function cancel(){try{await api(`/jobs/${job!.id}/cancel`,{});setJob({...job,status:'cancelled'});refreshHistory();}catch(e){setError((e as Error).message);}}
 const current=job;const activeIndex=current?stages.indexOf(current.status==='verified'?'verify':current.status==='submitted'?'submit':current.status):-1;
 return <div className="app-shell">
  <aside className="sidebar"><a className="brand" href="/" aria-label="PatchGoblin home"><div className="brand-icon"><Mascot small/></div><span>PatchGoblin<span className="brand-dot">.</span></span></a><div className="workspace-tag"><span className="live-dot"/> PYTHON CI WORKSPACE</div><nav aria-label="Main navigation">{[{id:'workbench',icon:Layers3,label:'Workbench'},{id:'history',icon:History,label:'Run history'},{id:'guide',icon:BookOpen,label:'Field guide'}].map(({id,icon:Icon,label})=><button key={id} onClick={()=>setPage(id)} className={page===id?'nav-link selected':'nav-link'}><Icon size={18}/>{label}{id==='workbench'&&<span className="nav-indicator"/>}</button>)}</nav><div className="sidebar-section">CONNECTED WORKSPACE</div><div className="connection"><GitFork size={17}/><div><strong>{bootstrap?.login||'GitHub connection'}</strong><span>{bootstrap?.connected?'Repository access verified':'Checking integration…'}</span></div><span className={bootstrap?.connected?'live-dot':'muted-dot'}/></div><div className="sidebar-bottom"><div className="goblin-note"><Mascot/><strong>Small patches.<br/>Strong evidence.</strong><p>A little goblin with a very strict checklist.</p><span><ShieldCheck size={14}/> Tests stay intact</span></div><a className="source-link" href="https://github.com/wauul/PatchGoblin" target="_blank" rel="noreferrer"><Code2 size={15}/> View source <ArrowUpRight size={14}/></a><div className="version">PatchGoblin v1.0 <span>pip + uv</span></div></div></aside>
  <main><header className="topbar"><div><span className="breadcrumb">Workspace</span><ChevronRight size={13}/><strong>{page==='workbench'?'Workbench':page==='history'?'Run history':'Field guide'}</strong></div><div className="topbar-status"><span className="live-dot"/>{bootstrap?.connected?'GitHub connected':'Private workspace'}<span className="avatar">{bootstrap?.login?.slice(0,1).toUpperCase()||'P'}</span></div></header>
  <div className="content">
   {error&&<div className="error" role="alert"><TriangleAlert size={17}/><span>{error}</span><button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
   {page==='workbench'&&<><div className="page-heading"><div><div className="eyebrow"><span/> YOUR CI, BACK ON TRACK</div><h1>Give your pipeline a little help.</h1><p>Find the failure. Make the smallest patch. Prove it works.</p></div><button className="secondary demo-button" onClick={()=>{setDemo(true);setJob(demoJob);setTab('diagnosis');}}>Explore demo <ArrowUpRight size={16}/></button></div>
    <section className="launch-panel" aria-label="Start an agent job"><div className="panel-heading"><div className="section-number">01</div><h2>Set the goblin to work</h2><span className="chip">Python only</span></div><div className="mode-options"><button onClick={()=>setMode('repair')} className={mode==='repair'?'mode active':'mode'}><span className="mode-icon"><Wrench size={20}/></span><span><strong>Repair a pipeline</strong><small>Diagnose a failed dependency install</small></span><span className="radio">{mode==='repair'&&<span/>}</span></button><button onClick={()=>setMode('builder')} className={mode==='builder'?'mode active':'mode'}><span className="mode-icon"><Plus size={22}/></span><span><strong>Build a pipeline</strong><small>Create CI from your project’s conventions</small></span><span className="radio">{mode==='builder'&&<span/>}</span></button></div>
    <div className="form-grid"><label>Repository<div className="select-wrap"><GitBranch size={16}/><select value={repo} onChange={e=>setRepo(e.target.value)} aria-label="Repository"><option value="" disabled>Select repository</option>{bootstrap?.repositories?.map((r:any)=><option key={r.name} value={r.name}>{r.name}{r.demo?' · seeded lab':''}</option>)}</select></div></label>{mode==='repair'?<label>Failed workflow run<div className="select-wrap"><Clock size={16}/><select value={run} onChange={e=>setRun(e.target.value)} aria-label="Failed workflow run"><option value="">{runs.length?'Choose a run':'No failed runs found'}</option>{runs.map(r=><option key={r.id} value={r.id}>{r.name} · {r.branch} · #{r.id}</option>)}</select></div></label>:<label>Base branch<div className="select-wrap"><GitBranch size={16}/><input value={ref} onChange={e=>setRef(e.target.value)} aria-label="Base branch" placeholder="main"/></div></label>}<button className="primary launch" onClick={start} disabled={busy||!bootstrap?.connected||!repo||(mode==='repair'&&!run)||(!!current&&!demo&&!finished.includes(current.status))}>{busy?<Loader2 className="spin" size={17}/>:<Sparkles size={17}/>} {mode==='repair'?'Investigate failure':'Build Python CI'} <ArrowRight size={17}/></button></div><div className="launch-foot"><span><ShieldCheck size={14}/> Isolated execution · No auto-merge · Required checks preserved</span><span>6 steps / 2 patches / 10 min max</span></div></section>
    {demo&&<div className="demo-notice"><FlaskConical size={17}/><span><strong>Illustrative demo.</strong> This walkthrough uses no model credits and executes no repository code. Start a seeded lab job above to see real agent work.</span><button onClick={()=>{setDemo(false);setJob(null);}} aria-label="Close demo"><X size={16}/></button></div>}
    <div className="results-heading"><div><div className="section-number">02</div><h2>{current?'Investigation workspace':'Ready when you are'}</h2></div>{current&&<span className={'status '+current.status}><span/> {current.status==='demo'?'Demo walkthrough':current.status}</span>}</div>
    {!current?<section className="empty-workspace"><div className="empty-visual"><Mascot/><span className="orbit one"><Terminal size={17}/></span><span className="orbit two"><Check size={17}/></span></div><h3>A clean slate for your next green build.</h3><p>Select a repository and a failed run, or let PatchGoblin<br className="desktop-break"/> build CI for a project that doesn’t have it yet.</p><button className="text-button" onClick={()=>{setDemo(true);setJob(demoJob);}}>See how an investigation works <ArrowRight size={15}/></button><div className="empty-points"><span><GitBranch size={16}/>Immutable commit</span><span><FlaskConical size={16}/>Reproduce first</span><span><GitPullRequest size={16}/>Verified PR</span></div></section>:<>
    <div className="pipeline" aria-label="Agent stages">{stages.map((s,i)=><div key={s} className={i<activeIndex?'stage done':i===activeIndex?'stage current':'stage'}><span>{i<activeIndex?<Check size={13}/>:String(i+1).padStart(2,'0')}</span><strong>{s}</strong>{i<5&&<div className="stage-line"/>}</div>)}</div>
    <div className="investigation-grid"><section className="evidence-panel"><div className="job-meta"><div><GitBranch size={15}/><strong>{current.repo}</strong><span>{current.base_ref||ref}</span></div><small>{current.sha?.slice(0,10)||'Queued'} {current.id?`· Job #${current.id}`:''}</small></div><div className="tabs" role="tablist" aria-label="Job evidence">{[{id:'diagnosis',icon:Sparkles,label:'Diagnosis'},{id:'diff',icon:FileDiff,label:'Patch diff'},{id:'verification',icon:CheckCircle2,label:'Verification'}].map(({id,icon:Icon,label})=><button role="tab" aria-selected={tab===id} key={id} onClick={()=>setTab(id)} className={tab===id?'tab active':'tab'}><Icon size={15}/>{label}{id==='diff'&&Object.keys(current.patch||{}).length>0&&<span>{Object.keys(current.patch).length}</span>}</button>)}</div>
    <div className="tab-content" role="tabpanel">{tab==='diagnosis'&&<><div className="diagnosis-label"><span className="mini-square"><Sparkles size={15}/></span><span>{current.category||'AGENT DIAGNOSIS'}</span></div><h3>{current.status==='queued'?'Your investigation is in the queue.':current.status==='failed'?'Investigation stopped safely.':current.status==='unsupported'?'This failure needs a different approach.':current.status==='cancelled'?'Investigation cancelled.':'Follow the evidence.'}</h3><p className="diagnosis-text">{current.diagnosis||'The worker is collecting evidence. Updates are saved as the investigation progresses.'}</p>{current.evidence?.length>0&&<div className="evidence-list"><h4>SUPPORTING EVIDENCE</h4>{current.evidence.map((e:string,i:number)=><div key={i}><span>{i+1}</span><p>{e}</p></div>)}</div>}{current.limitations?.length>0&&<div className="limitations"><ShieldCheck size={17}/><div><strong>Verification boundaries</strong>{current.limitations.map((l:string,i:number)=><p key={i}>{l}</p>)}</div></div>}</>}
    {tab==='diff'&&(current.diff?<><div className="diff-title"><Code2 size={15}/><strong>{Object.keys(current.patch).join(', ')}</strong><span>Proposed changes</span></div><pre className="diff">{current.diff.split('\n').map((l:string,i:number)=><div key={i} className={l.startsWith('+')&&!l.startsWith('+++')?'added':l.startsWith('-')&&!l.startsWith('---')?'removed':l.startsWith('@@')?'hunk':''}><span className="line-no">{i+1}</span>{l||' '}</div>)}</pre></>:<div className="tab-empty"><FileDiff size={26}/><h3>No patch yet</h3><p>The agent only proposes a patch when the evidence supports one.</p></div>)}
    {tab==='verification'&&<><h3>Every check has a receipt.</h3><p className="muted">Original reproduction and patched verification are reported separately.</p>{current.reproduction?.length>0&&<div className="check-group"><h4>ORIGINAL REPRODUCTION</h4>{current.reproduction.map((v:any,i:number)=><CheckRow key={i} value={v}/>)}</div>}<div className="check-group"><h4>PATCHED SANDBOX CHECKS</h4>{current.verification?.length?current.verification.map((v:any,i:number)=><CheckRow key={i} value={v}/>):<p className="muted">No patched checks have been recorded.</p>}</div><div className="check-group"><h4>REMOTE GITHUB ACTIONS</h4>{current.remote_ci?.length?current.remote_ci.map((r:any,i:number)=><a className="remote-run" key={i} href={r.url} target="_blank" rel="noreferrer"><span className={r.conclusion==='success'?'green':'muted'}>{r.conclusion==='success'?<CheckCircle2 size={17}/>:<Clock size={17}/>}</span>{r.name}<span>{r.conclusion||r.status}</span><ArrowUpRight size={14}/></a>):<p className="muted">Remote CI has not been confirmed.</p>}</div></>}
    </div>{current.pr_url&&<a href={current.pr_url} target="_blank" rel="noreferrer" className="pr-banner"><GitPullRequest size={19}/><div><strong>Verified patch, ready for review</strong><span>Pull request #{current.pr_number} · You decide when to merge.</span></div><ArrowUpRight size={18}/></a>}</section>
    <aside className="activity-panel"><div className="activity-heading"><h3>Goblin activity</h3>{!demo&&!finished.includes(current.status)&&<Loader2 size={16} className="spin"/>}</div><div className="events" aria-live="polite">{current.events?.length?current.events.map((e:any,i:number)=><div className="event" key={i}><span className="event-point"/><div><strong>{e.stage}</strong><p>{e.message}</p></div></div>):<div className="event"><span className="event-point"/><div><strong>queued</strong><p>Waiting for the next available worker.</p></div></div>}</div><div className="metrics"><div><Clock size={14}/><span>Duration</span><strong>{duration(current.metrics?.duration_seconds)}</strong></div><div><Sparkles size={14}/><span>Model tokens</span><strong>{current.metrics?.model_tokens?.toLocaleString()??'Unavailable'}</strong></div><div><Terminal size={14}/><span>Tool calls</span><strong>{current.metrics?.tool_calls??'Unavailable'}</strong></div><div><span className="dollar">$</span><span>Estimated cost</span><strong>{current.metrics?.estimated_cost_usd==null?'Unavailable':`$${current.metrics.estimated_cost_usd}`}</strong></div></div>{!demo&&!finished.includes(current.status)&&<button className="cancel" onClick={cancel}><X size={14}/>Cancel investigation</button>}{current.run_url&&<a className="text-button" href={current.run_url} target="_blank" rel="noreferrer">Original workflow <ArrowUpRight size={14}/></a>}</aside></div></>}
    <div className="workbench-footer"><span><ShieldCheck size={15}/> Evidence before edits. Verification before pull requests.</span><span>Built for pip & uv <span className="footer-spark">✦</span></span></div>
   </>}
   {page==='history'&&<><div className="page-heading"><div><div className="eyebrow">YOUR INVESTIGATION LOG</div><h1>Every run leaves a trail.</h1><p>Jobs and their evidence persist across refreshes.</p></div><button className="secondary" onClick={refreshHistory}><RotateCw size={16}/>Refresh</button></div><section className="history-panel">{history.length?history.map(h=><button key={h.id} className="history-row" onClick={()=>load(h.id)}><span className="mode-icon">{h.mode==='repair'?<Wrench size={18}/>:<Plus size={18}/>}</span><span><strong>{h.repo}</strong><small>{h.mode} · Job #{h.id} · {new Date(h.created_at).toLocaleString()}</small></span><span className="history-status">{h.status}</span><ArrowRight size={17}/></button>):<div className="tab-empty"><History size={28}/><h3>Your first investigation starts here.</h3><p>Live runs appear here after you start a job.</p><button className="primary" onClick={()=>setPage('workbench')}>Go to workbench <ArrowRight size={16}/></button></div>}</section></>}
   {page==='guide'&&<><div className="page-heading"><div><div className="eyebrow">THE GOBLIN’S OPERATING MANUAL</div><h1>Helpful, within clear boundaries.</h1><p>A bounded agent for Python dependency failures and missing CI.</p></div></div><div className="guide-grid"><article><Wrench size={25}/><h2>Repair mode</h2><p>Reproduces a failed GitHub Actions run at its original commit, investigates dependency evidence, and tests a minimal patch.</p><ul><li>Missing declared packages</li><li>Conflicting dependency constraints</li><li>Python version mismatches</li><li>Incorrect installation commands</li><li>uv lock drift with deterministic refresh</li></ul></article><article><Plus size={25}/><h2>Builder mode</h2><p>Inspects pip or uv metadata, existing tests and lint configuration. Adds a minimally permissioned workflow and verifies the same commands in isolation.</p><p>If there are no tests, that limitation stays visible. Existing workflows are preserved.</p></article><article><ShieldCheck size={25}/><h2>Safety is part of the workflow</h2><p>One worker at a time. Six investigations, two patch attempts, 12,000 model tokens, and ten minutes per job. Repository code runs without credentials in a disposable Docker container.</p><p>Installation network access is limited to PyPI through a proxy. Checks run with networking disabled.</p></article><article><TriangleAlert size={25}/><h2>When the goblin stops</h2><p>Application bugs, assertion failures, credentials, network outages, custom shell commands, services, matrix jobs, and private repositories require another approach in this deployment.</p><p>Unsupported and unverified results never become successful repairs.</p></article></div><section className="guide-note"><FlaskConical size={23}/><div><h3>About the seeded lab</h3><p>The connected lab is a public demonstration repository with intentional failures. These are real GitHub workflows and model executions, labeled as seeded data. The illustrative demo is a separate walkthrough that executes nothing.</p></div><a href="https://github.com/wauul/PatchGoblin#readme" target="_blank" rel="noreferrer" className="secondary">Read the README <ArrowUpRight size={15}/></a></section></>}
  </div></main>
 </div>;
}
function CheckRow({value:v}:{value:any}){return <details className="check-row"><summary><span className={v.exit_code===0?'green':'red'}>{v.exit_code===0?<CheckCircle2 size={17}/>:<TriangleAlert size={17}/>}</span><code>{v.command}</code><span>{v.exit_code===0?'Passed':`Exit ${v.exit_code}`}</span><small>{duration(v.duration_seconds)}</small></summary><pre>{v.logs||'Command completed without diagnostic output.'}</pre><small>Network: {v.network||'Unavailable'}</small></details>}
createRoot(document.getElementById('root')!).render(<App/>);
